window.quizRegistry = window.quizRegistry || {};
window.quizRegistry['Os'] ={
    title: "Os Reviewer Lesson 1 - 3",
    data:[
          // LESSON 1
  { sec: 'Lesson 1: Computer System Architecture & Hardware', q: "1. A set of hardware and software components that work together to accept input, process data, and produce output.", ans: "Computer System", alt: ["Computer Systems"] },
  { sec: 'Lesson 1', q: "2. The functional layer made up of physical components that do the actual work.", ans: "Hardware" },
  { sec: 'Lesson 1', q: "3. The functional layer that controls and coordinates hardware use and provides a stable platform for other software.", ans: "Operating System", alt: ["OS"] },
  { sec: 'Lesson 1', q: "4. The functional layer made up of software that solves user problems.", ans: "Application Programs", alt: ["Application Software", "Applications", "Apps"] },
  { sec: 'Lesson 1', q: "5. The functional layer consisting of people, machines, or other computers that issue requests.", ans: "Users", alt: ["User"] },
  { sec: 'Lesson 1', q: "6. The component that executes instructions and contains the ALU, control unit, and registers.", ans: "CPU", alt: ["Central Processing Unit", "Processor"] },
  { sec: 'Lesson 1', q: "7. Volatile storage that holds data and instructions the CPU is actively using.", ans: "Main Memory", alt: ["RAM", "Primary Memory", "Primary Storage", "Random Access Memory"] },
  { sec: 'Lesson 1', q: "8. The set of pathways connecting the CPU, memory, and I/O devices.", ans: "System Bus", alt: ["Bus"] },
  { sec: 'Lesson 1', q: "9. Small processors attached to each I/O device that manage that device's operation.", ans: "Device Controllers", alt: ["Device Controller", "Controller"] },
  { sec: 'Lesson 1', q: "10. The organizational concept in which devices signal the CPU when they need service.", ans: "Interrupts", alt: ["Interrupt"] },
  { sec: 'Lesson 1', q: "11. The method of constantly checking whether a device needs attention.", ans: "Polling", alt: ["Busy Waiting", "Poll"] },
  { sec: 'Lesson 1', q: "12. The small routine the CPU jumps to in order to deal with an interrupt request.", ans: "Interrupt Handler", alt: ["Interrupt Service Routine", "ISR"] },
  { sec: 'Lesson 1', q: "13. The architecture proposed by John von Neumann in 1945.", ans: "Von Neumann Architecture" },
  { sec: 'Lesson 1', q: "14. The defining principle in which program instructions and data are stored together in the same memory.", ans: "Stored-Program Concept", alt: ["Stored Program", "Stored Program Concept"] },
  { sec: 'Lesson 1', q: "15. The main part of a computer that controls how it works and handles instructions from programs.", ans: "CPU", alt: ["Central Processing Unit", "Processor"] },
  { sec: 'Lesson 1', q: "16. The CPU component that sends control signals, controls data movement, and fetches instructions from memory.", ans: "Control Unit", alt: ["CU"] },
  { sec: 'Lesson 1', q: "17. The CPU component that performs arithmetic operations, logical operations, comparisons, and bit shifting.", ans: "Arithmetic and Logic Unit", alt: ["ALU", "Arithmetic Logic Unit"] },
  { sec: 'Lesson 1', q: "18. The fastest type of memory located inside the CPU.", ans: "Registers", alt: ["Register"] },
  { sec: 'Lesson 1', q: "19. The register that keeps track of the address of the next instruction to be executed.", ans: "Program Counter", alt: ["PC", "Instruction Pointer", "IP"] },
  { sec: 'Lesson 1', q: "20. The register that holds the current instruction being executed.", ans: "Instruction Register", alt: ["IR"] },
  { sec: 'Lesson 1', q: "21. The register that stores the address of the memory location being accessed.", ans: "Memory Address Register", alt: ["MAR"] },
  { sec: 'Lesson 1', q: "22. The register that temporarily holds data being transferred to or from memory.", ans: "Memory Data Register", alt: ["MDR", "Memory Buffer Register", "MBR"] },
  { sec: 'Lesson 1', q: "23. The register that stores intermediate results of arithmetic and logic operations.", ans: "Accumulator", alt: ["AC", "ACC"] },
  { sec: 'Lesson 1', q: "24. Registers used for temporary storage of data during processing.", ans: "General Purpose Registers", alt: ["GPR", "General-Purpose Registers", "General Purpose Register"] },
  { sec: 'Lesson 1', q: "25. The communication system that transfers data, addresses, and control signals between the CPU, memory, and I/O devices.", ans: "Bus", alt: ["System Bus"] },
  { sec: 'Lesson 1', q: "26. The component that connects the CPU and memory to input/output devices.", ans: "I/O Interface", alt: ["Input/Output Interface", "IO Interface", "I/O Interfaces"] },
  { sec: 'Lesson 1', q: "27. The performance limitation created because instructions and data share the same bus and memory.", ans: "Von Neumann Bottleneck" },
  { sec: 'Lesson 1', q: "28. The repeating computer-operation cycle made up of fetch, decode, execute, and store/update.", ans: "Fetch-Decode-Execute Cycle", alt: ["Instruction Cycle", "Machine Cycle", "Fetch Decode Execute Cycle"] },
  { sec: 'Lesson 1', q: "29. The step in the cycle where the Control Unit retrieves the next instruction from memory.", ans: "Fetch" },
  { sec: 'Lesson 1', q: "30. The step in the cycle where the instruction is translated into a form the ALU and other components understand.", ans: "Decode" },
  { sec: 'Lesson 1', q: "31. The step in the cycle where the ALU or relevant component carries out the instruction.", ans: "Execute" },
  { sec: 'Lesson 1', q: "32. The step in the cycle where results are written back and the Program Counter is updated.", ans: "Store/Update", alt: ["Store", "Update", "Writeback", "Write Back"] },
  { sec: 'Lesson 1', q: "33. The OS operation model that uses interrupts and traps to regain control of the CPU.", ans: "Interrupt-Driven Operation", alt: ["Interrupt Driven Operation", "Interrupt Driven"] },
  { sec: 'Lesson 1', q: "34. The operation model in which hardware supports a user mode and a kernel mode.", ans: "Dual-Mode Operation", alt: ["Dual Mode Operation", "Dual Mode"] },
  { sec: 'Lesson 1', q: "35. The request ordinary programs must use to ask the OS to perform privileged operations.", ans: "System Call", alt: ["Syscall"] },

  // LESSON 2
  { sec: 'Lesson 2: Operating System Services, Interfaces & Structures', q: "36. The layer through which a user interacts with the operating system.", ans: "User Interface", alt: ["UI"] },
  { sec: 'Lesson 2', q: "37. The text-based interface in which a user types commands such as Bash or PowerShell.", ans: "Command-Line Interface", alt: ["CLI", "Command Line Interface"] },
  { sec: 'Lesson 2', q: "38. The visual interface that uses windows, icons, menus, and pointers.", ans: "Graphical User Interface", alt: ["GUI"] },
  { sec: 'Lesson 2', q: "39. The model named by the initials for windows, icons, menus, and pointers.", ans: "WIMP Model", alt: ["WIMP"] },
  { sec: 'Lesson 2', q: "40. The interface in which commands are submitted as jobs with no interactive session.", ans: "Batch Interface", alt: ["Batch"] },
  { sec: 'Lesson 2', q: "41. The OS service that loads a program into memory and runs it.", ans: "Program Execution" },
  { sec: 'Lesson 2', q: "42. The OS service that manages operations users cannot directly perform on hardware.", ans: "I/O Operations", alt: ["Input/Output Operations", "IO Operations"] },
  { sec: 'Lesson 2', q: "43. The OS service for creating, deleting, reading, writing, and organizing files/directories.", ans: "File System Manipulation", alt: ["File Manipulation", "File-System Manipulation"] },
  { sec: 'Lesson 2', q: "44. The OS service that lets processes exchange information on the same machine or over a network.", ans: "Communications", alt: ["Communication", "IPC"] },
  { sec: 'Lesson 2', q: "45. The OS service that detects and handles errors in CPU, memory, I/O devices, or user programs.", ans: "Error Detection" },
  { sec: 'Lesson 2', q: "46. The system-facing service that allocates CPU time, memory, storage, and I/O devices among users/jobs.", ans: "Resource Allocation" },
  { sec: 'Lesson 2', q: "47. The service that tracks which users/programs use which resources for billing, optimization, or auditing.", ans: "Accounting" },
  { sec: 'Lesson 2', q: "48. The service that controls access to resources, prevents process interference, and authenticates users.", ans: "Protection and Security", alt: ["Security and Protection"] },
  { sec: 'Lesson 2', q: "49. The programming interface through which a running program requests a service from the OS kernel.", ans: "System Call", alt: ["Syscall"] },
  { sec: 'Lesson 2', q: "50. The restricted mode where application code runs.", ans: "User Mode" },
  { sec: 'Lesson 2', q: "51. The privileged mode where the operating system runs.", ans: "Kernel Mode", alt: ["Supervisor Mode", "System Mode"] },
  { sec: 'Lesson 2', q: "52. The special CPU instruction that switches the CPU from user mode to kernel mode during a system call.", ans: "Trap", alt: ["Software Interrupt"] },
  { sec: 'Lesson 2', q: "53. The number used by the OS to look up a requested service in the system call table.", ans: "System Call Number" },
  { sec: 'Lesson 2', q: "54. One parameter-passing method that places parameters directly in CPU storage locations.", ans: "Registers", alt: ["Register"] },
  { sec: 'Lesson 2', q: "55. One parameter-passing method that stores parameters in a block/table in memory and passes its address.", ans: "Block/Table in Memory", alt: ["Block in Memory", "Table in Memory", "Block or Table in Memory", "Memory Block"] },
  { sec: 'Lesson 2', q: "56. One parameter-passing method that pushes parameters onto this data structure.", ans: "Stack" },
  { sec: 'Lesson 2', q: "57. The system-call category used to create, terminate, and manage processes.", ans: "Process Control" },
  { sec: 'Lesson 2', q: "58. The system-call category used to create, read, write, and delete files.", ans: "File Management" },
  { sec: 'Lesson 2', q: "59. The system-call category used to request/release devices and perform read/write operations.", ans: "Device Management" },
  { sec: 'Lesson 2', q: "60. The system-call category used to get or set system data.", ans: "Information Maintenance" },
  { sec: 'Lesson 2', q: "61. The system-call category used for message passing and shared memory.", ans: "Communications", alt: ["Communication"] },
  { sec: 'Lesson 2', q: "62. The system-call category used to control access to resources.", ans: "Protection" },
  { sec: 'Lesson 2', q: "63. The part of OS design that describes how to do something or the machinery used.", ans: "Mechanism", alt: ["Mechanisms"] },
  { sec: 'Lesson 2', q: "64. The part of OS design that decides what should be done.", ans: "Policy", alt: ["Policies"] },
  { sec: 'Lesson 2', q: "65. The implementation consideration describing how easily an OS can be moved to new hardware.", ans: "Portability" },
  { sec: 'Lesson 2', q: "66. The OS structure in which the entire OS runs as a single program in kernel mode.", ans: "Monolithic Structure", alt: ["Monolithic Kernel", "Monolithic"] },
  { sec: 'Lesson 2', q: "67. The OS structure divided into layers where each layer uses services of the layer directly beneath it.", ans: "Layered Approach", alt: ["Layered Structure", "Layered"] },
  { sec: 'Lesson 2', q: "68. The OS structure that keeps only basic IPC, minimal memory management, and minimal scheduling in the kernel.", ans: "Microkernel Structure", alt: ["Microkernel"] },
  { sec: 'Lesson 2', q: "69. The approach that uses dynamically loadable kernel modules.", ans: "Modular Approach", alt: ["Loadable Kernel Modules", "LKM", "Modules"] },
  { sec: 'Lesson 2', q: "70. The type of modern OS structure that mixes elements of several structural models.", ans: "Hybrid Systems", alt: ["Hybrid Structure", "Hybrid System"] },

  // LESSON 3
  { sec: 'Lesson 3: Processes, PCB, States & Multiprogramming', q: "71. A passive entity consisting of an executable file sitting on disk, with instructions and data.", ans: "Program" },
  { sec: 'Lesson 3', q: "72. An active entity that is a program in execution, with its own state, registers, memory, and resources.", ans: "Process" },
  { sec: 'Lesson 3', q: "73. The data structure the OS uses to represent and manage each process.", ans: "Process Control Block", alt: ["PCB"] },
  { sec: 'Lesson 3', q: "74. Another name for the Process Control Block.", ans: "Task Control Block", alt: ["TCB"] },
  { sec: 'Lesson 3', q: "75. The PCB field containing the current state such as new, ready, running, waiting, or terminated.", ans: "Process State" },
  { sec: 'Lesson 3', q: "76. The unique identifier for a process.", ans: "Process ID", alt: ["PID", "Process Identifier"] },
  { sec: 'Lesson 3', q: "77. The PCB field containing the address of the next instruction to execute.", ans: "Program Counter", alt: ["PC"] },
  { sec: 'Lesson 3', q: "78. The PCB field containing a snapshot of register contents at the moment of interruption.", ans: "CPU Registers", alt: ["Registers"] },
  { sec: 'Lesson 3', q: "79. The PCB field containing priority and pointers to scheduling queues.", ans: "CPU Scheduling Information", alt: ["Scheduling Information"] },
  { sec: 'Lesson 3', q: "80. The PCB field containing base/limit registers, page tables, or segment tables.", ans: "Memory Management Information", alt: ["Memory-Management Information"] },
  { sec: 'Lesson 3', q: "81. The PCB field containing CPU time used, time limits, and process number.", ans: "Accounting Information" },
  { sec: 'Lesson 3', q: "82. The PCB field containing allocated I/O devices and open files.", ans: "I/O Status Information", alt: ["IO Status Information", "Input/Output Status Information"] },
  { sec: 'Lesson 3', q: "83. The mechanism used to store and restore CPU state so a process can resume from the same point later.", ans: "Context Switching", alt: ["Context Switch"] },
  { sec: 'Lesson 3', q: "84. The operation that occurs when the CPU switches from executing one process to another.", ans: "Context Switch", alt: ["Context Switching"] },
  { sec: 'Lesson 3', q: "85. The kind of work context switching is considered because no useful process instruction is executed during the switch itself.", ans: "Pure Overhead", alt: ["Overhead"] },
  { sec: 'Lesson 3', q: "86. The process state in which the process is being created.", ans: "New" },
  { sec: 'Lesson 3', q: "87. The process state in which the process is loaded into memory and waiting to be assigned to the CPU.", ans: "Ready" },
  { sec: 'Lesson 3', q: "88. The process state in which instructions are actively being executed by the CPU.", ans: "Running" },
  { sec: 'Lesson 3', q: "89. The process state in which a process waits for an event such as I/O completion or a signal.", ans: "Waiting", alt: ["Blocked", "Waiting (Blocked)"] },
  { sec: 'Lesson 3', q: "90. The process state in which the process has finished execution.", ans: "Terminated" },
  { sec: 'Lesson 3', q: "91. The extension of the basic five-state model in which processes are temporarily removed from main memory or the active set.", ans: "Suspend States", alt: ["Suspended States", "Suspend State"] },
  { sec: 'Lesson 3', q: "92. The suspended state of a process that was ready to run before being removed from main memory.", ans: "Suspend Ready State", alt: ["Suspend Ready", "Suspended Ready"] },
  { sec: 'Lesson 3', q: "93. The suspended state of a process that was already waiting for an event before being moved out of main memory.", ans: "Suspend Wait State", alt: ["Suspend Wait", "Suspended Wait", "Suspend Blocked"] },
  { sec: 'Lesson 3', q: "94. The transition that occurs when the OS finishes creating a process, allocates its PCB and memory, and admits it.", ans: "New to Ready", alt: ["New -> Ready", "Admit"] },
  { sec: 'Lesson 3', q: "95. The transition that occurs when the scheduler/dispatcher selects a process to run on the CPU.", ans: "Ready to Running", alt: ["Ready -> Running", "Dispatch", "Schedule"] },
  { sec: 'Lesson 3', q: "96. The transition that occurs when a running process requests I/O or must wait for an event/resource.", ans: "Running to Waiting", alt: ["Running -> Waiting"] },
  { sec: 'Lesson 3', q: "97. The transition that occurs when an interrupt happens and the running process is paused but can still run.", ans: "Running to Ready", alt: ["Running -> Ready"] },
  { sec: 'Lesson 3', q: "98. The transition that occurs when the event a waiting process needed has occurred.", ans: "Waiting to Ready", alt: ["Waiting -> Ready"] },
  { sec: 'Lesson 3', q: "99. The transition that occurs when a process finishes execution or is aborted.", ans: "Running to Terminated", alt: ["Running -> Terminated", "Exit"] },
  { sec: 'Lesson 3', q: "100. The type of process that spends most of its time doing computation and issues few I/O requests.", ans: "CPU-Bound Process", alt: ["CPU Bound Process", "CPU Bound"] },
  { sec: 'Lesson 3', q: "101. The type of process that spends most of its time waiting for I/O and uses short CPU bursts.", ans: "I/O-Bound Process", alt: ["IO Bound Process", "IO-Bound Process", "I/O Bound"] },
  { sec: 'Lesson 3', q: "102. The type of process that cannot affect or be affected by other processes and does not share data.", ans: "Independent Process", alt: ["Independent"] },
  { sec: 'Lesson 3', q: "103. The type of process that can affect or be affected by other processes and shares data.", ans: "Cooperating Process", alt: ["Cooperating"] },
  { sec: 'Lesson 3', q: "104. Processes that run in user mode and are initiated by user actions or user programs.", ans: "User Processes", alt: ["User Process"] },
  { sec: 'Lesson 3', q: "105. Processes that run in the background, often start at boot, and provide system services.", ans: "System Processes", alt: ["Kernel Processes", "Daemons", "Services", "System/Kernel Processes"] },
  { sec: 'Lesson 3', q: "106. The technique of keeping multiple processes in memory so the CPU can switch to another ready process when one waits.", ans: "Multiprogramming" },
  { sec: 'Lesson 3', q: "107. The main reason multiprogramming matters, described as keeping the CPU from sitting idle.", ans: "CPU Utilization", alt: ["CPU Utilization / Efficiency"] },
  { sec: 'Lesson 3', q: "108. An extension of multiprogramming in which the CPU switches frequently using time slices for responsiveness.", ans: "Multitasking", alt: ["Time-Sharing", "Time Sharing", "Multitasking (Time-Sharing)"] },
  { sec: 'Lesson 3', q: "109. The number of processes in memory at once.", ans: "Degree of Multiprogramming" },
  { sec: 'Lesson 3', q: "110. The collection from which the OS selects processes and loads a subset into memory.", ans: "Job Pool" }
    ]
}