window.quizRegistry = window.quizRegistry || {};
window.quizRegistry['PL2'] ={
    title: "PL lesson 2 Reviewer",
    data:[
  {
    "sec": "Front-End Compiler Architecture",
    "q": "What is Stage 1 in the front-end compiler architecture pipeline?",
    "ans": "Source Text",
    "alt": [
      "Source Text Stage"
    ]
  },
  {
    "sec": "Front-End Compiler Architecture",
    "q": "Which front-end compiler component converts the raw source text into a token stream?",
    "ans": "Lexical Analyzer",
    "alt": [
      "Scanner",
      "Lexer",
      "Scanner / Lexer"
    ]
  },
  {
    "sec": "Front-End Compiler Architecture",
    "q": "What output is generated by the Lexical Analyzer for the Parser to consume?",
    "ans": "Token Stream",
    "alt": [
      "Typed Symbols",
      "Token Stream / Typed Symbols"
    ]
  },
  {
    "sec": "Front-End Compiler Architecture",
    "q": "Which component acts as the syntax validator in the compiler front-end pipeline?",
    "ans": "Parser",
    "alt": [
      "Syntax Validator"
    ]
  },
  {
    "sec": "Front-End Compiler Architecture",
    "q": "What tree structure is generated as output by the Parser?",
    "ans": "Abstract Syntax Tree",
    "alt": [
      "AST"
    ]
  },
  {
    "sec": "Compiler Stages",
    "q": "Which compilation stage checks type correctness, variable bindings, and scope boundaries?",
    "ans": "Semantic Analysis",
    "alt": [
      "Stage 4: Semantic Analysis"
    ]
  },
  {
    "sec": "Compiler Stages",
    "q": "Which compilation stage enforces grammatical structure and builds an explicit Parse Tree or AST?",
    "ans": "Syntax Analysis",
    "alt": [
      "Stage 3: Syntax Analysis"
    ]
  },
  {
    "sec": "Lexing vs Parsing",
    "q": "What component is responsible for stripping whitespace and comments from source code?",
    "ans": "Lexical Analyzer",
    "alt": [
      "Scanner",
      "Lexer"
    ]
  },
  {
    "sec": "Lexing vs Parsing",
    "q": "What component enforces operator precedence and associativity?",
    "ans": "Parser",
    "alt": [
      "Syntax Analyzer"
    ]
  },
  {
    "sec": "Lexical Analysis",
    "q": "What term refers to the raw, unstructured input processing format read directly from disk or memory?",
    "ans": "Input Character Stream",
    "alt": [
      "Source Text"
    ]
  },
  {
    "sec": "Lexical Analysis",
    "q": "What non-functional characters does the lexer strip during noise removal?",
    "ans": "Whitespace and comments",
    "alt": [
      "Spaces, tabs, newlines, and comments"
    ]
  },
  {
    "sec": "Lexical Analysis",
    "q": "What metadata does a lexer attach to tokens for precise compiler error reporting?",
    "ans": "Row and column metadata",
    "alt": [
      "Line number and column offset",
      "Source position"
    ]
  },
  {
    "sec": "Tokenization Definitions",
    "q": "What is the abstract category assigned to a class of input units, such as NUMBER or IDENTIFIER?",
    "ans": "Token",
    "alt": []
  },
  {
    "sec": "Tokenization Definitions",
    "q": "What term refers to the literal substring or actual string of characters in the source code matching a token?",
    "ans": "Lexeme",
    "alt": []
  },
  {
    "sec": "Tokenization Definitions",
    "q": "What formal rule defines how a lexeme is matched or formed, typically using Regular Expressions?",
    "ans": "Pattern",
    "alt": []
  },
  {
    "sec": "Tokenization Definitions",
    "q": "What is the regular expression pattern given for matching an identifier?",
    "ans": "[a-zA-Z_][a-zA-Z0-9_]*",
    "alt": [
      "[a-zA-Z][a-zA-Z0-9_]*"
    ]
  },
  {
    "sec": "Tokenization Definitions",
    "q": "What is the regular expression pattern given for matching an integer?",
    "ans": "[0-9]+",
    "alt": []
  },
  {
    "sec": "Lexical Analysis Example",
    "q": "In the lexing example of `let total = price * 1.12;`, what token category is assigned to `let`?",
    "ans": "KEYWORD",
    "alt": [
      "KEYWORD (\"let\")"
    ]
  },
  {
    "sec": "Lexical Analysis Example",
    "q": "In the lexing example of `let total = price * 1.12;`, what token category is assigned to `total`?",
    "ans": "IDENTIFIER",
    "alt": [
      "IDENTIFIER (\"total\")"
    ]
  },
  {
    "sec": "Lexical Analysis Example",
    "q": "In the lexing example of `let total = price * 1.12;`, what token category is assigned to `=`?",
    "ans": "ASSIGN",
    "alt": [
      "ASSIGN (\"=\")"
    ]
  },
  {
    "sec": "Lexical Analysis Example",
    "q": "In the lexing example of `let total = price * 1.12;`, what token category is assigned to `*`?",
    "ans": "MULT",
    "alt": [
      "MULT (\"*\")"
    ]
  },
  {
    "sec": "Lexical Analysis Example",
    "q": "In the lexing example of `let total = price * 1.12;`, what token category is assigned to `1.12`?",
    "ans": "NUMBER",
    "alt": [
      "NUMBER (\"1.12\")"
    ]
  },
  {
    "sec": "Lexical Analysis Example",
    "q": "In the lexing example of `let total = price * 1.12;`, what token category is assigned to `;`?",
    "ans": "SEMICOLON",
    "alt": [
      "SEMICOLON (\";\")"
    ]
  },
  {
    "sec": "Grammar Rules",
    "q": "Which pattern-matching formal system is used by lexers to match linear, non-nested patterns?",
    "ans": "Regular Expressions",
    "alt": [
      "RegEx"
    ]
  },
  {
    "sec": "Grammar Rules",
    "q": "What key structural pattern can Regular Expressions NOT validate or match?",
    "ans": "Arbitrarily nested structures",
    "alt": [
      "Balanced parentheses",
      "Nested structures"
    ]
  },
  {
    "sec": "Grammar Rules",
    "q": "Which formal grammar system is used by parsers to define recursive language rules?",
    "ans": "Context-Free Grammars",
    "alt": [
      "CFG"
    ]
  },
  {
    "sec": "Context-Free Grammars",
    "q": "In the 4-tuple CFG definition G = (V, Σ, R, S), what does the set 'V' represent?",
    "ans": "Non-terminal symbols",
    "alt": [
      "Syntactic variables"
    ]
  },
  {
    "sec": "Context-Free Grammars",
    "q": "In the 4-tuple CFG definition G = (V, Σ, R, S), what does the set 'Σ' (Sigma) represent?",
    "ans": "Terminal symbols",
    "alt": [
      "Actual tokens",
      "Literals"
    ]
  },
  {
    "sec": "Context-Free Grammars",
    "q": "In the 4-tuple CFG definition G = (V, Σ, R, S), what does 'R' represent?",
    "ans": "Production Rules mapping",
    "alt": [
      "Production Rules"
    ]
  },
  {
    "sec": "Context-Free Grammars",
    "q": "In the 4-tuple CFG definition G = (V, Σ, R, S), what does 'S' represent?",
    "ans": "Start Symbol",
    "alt": [
      "The Start Symbol"
    ]
  },
  {
    "sec": "Grammar Specifications",
    "q": "What does the abbreviation BNF stand for in formal language syntax specification?",
    "ans": "Backus-Naur Form",
    "alt": []
  },
  {
    "sec": "Grammar Specifications",
    "q": "What does the abbreviation EBNF stand for?",
    "ans": "Extended Backus-Naur Form",
    "alt": [
      "Extended BNF"
    ]
  },
  {
    "sec": "EBNF Enhancements",
    "q": "In EBNF, what do curly braces `{A}` represent?",
    "ans": "Repetition",
    "alt": [
      "Zero or more repetitions"
    ]
  },
  {
    "sec": "EBNF Enhancements",
    "q": "In EBNF, what do square brackets `[A]` represent?",
    "ans": "Option",
    "alt": [
      "Optional inclusion"
    ]
  },
  {
    "sec": "EBNF Enhancements",
    "q": "In EBNF, what do parentheses `(A | B)` represent?",
    "ans": "Grouping",
    "alt": [
      "Choice selection"
    ]
  },
  {
    "sec": "Grammar Ambiguity",
    "q": "What is the condition where a grammar produces multiple valid parse trees for a single input string?",
    "ans": "Ambiguity",
    "alt": [
      "Grammar Ambiguity",
      "The Ambiguity Problem"
    ]
  },
  {
    "sec": "Grammar Ambiguity",
    "q": "In an ambiguous expression like `5 + 3 * 2`, what is the correct mathematical evaluation result?",
    "ans": "11",
    "alt": []
  },
  {
    "sec": "Grammar Ambiguity",
    "q": "In grammar stratification, where do lower-precedence operators (+, -) live in the production chain?",
    "ans": "Higher up",
    "alt": [
      "Higher up in the production chain"
    ]
  },
  {
    "sec": "Grammar Ambiguity",
    "q": "In grammar stratification, where do higher-precedence operators (*, /) live in the production chain?",
    "ans": "Deeper near the leaf operands",
    "alt": [
      "Deeper"
    ]
  },
  {
    "sec": "Parsing Techniques",
    "q": "What parser type classification is associated with LL parsing?",
    "ans": "Top-Down",
    "alt": [
      "Top-Down Parsing"
    ]
  },
  {
    "sec": "Parsing Techniques",
    "q": "What parser type classification is associated with LR parsing?",
    "ans": "Bottom-Up",
    "alt": [
      "Bottom-Up Parsing"
    ]
  },
  {
    "sec": "Parsing Techniques",
    "q": "Which derivation strategy starts from the Start Symbol S down to tokens?",
    "ans": "Top-Down",
    "alt": [
      "Top-Down Parsing",
      "LL Parsing"
    ]
  },
  {
    "sec": "Parsing Techniques",
    "q": "Which derivation strategy shift-reduces tokens up to the Start Symbol S?",
    "ans": "Bottom-Up",
    "alt": [
      "Bottom-Up Parsing",
      "LR Parsing"
    ]
  },
  {
    "sec": "Parsing Techniques",
    "q": "Which parsing approach has high hand-writability due to intuitive Recursive Descent?",
    "ans": "Top-Down",
    "alt": [
      "Top-Down Parsing",
      "LL Parsing"
    ]
  },
  {
    "sec": "Parsing Techniques",
    "q": "Name one parser generator tool mentioned for generating Bottom-Up (LR) parsers.",
    "ans": "Yacc",
    "alt": [
      "Bison",
      "ANTLR"
    ]
  },
  {
    "sec": "Parsing Techniques",
    "q": "Which parsing method CANNOT handle immediate left-recursion without transformation?",
    "ans": "Top-Down Parsing",
    "alt": [
      "LL Parsing",
      "Top-Down"
    ]
  },
  {
    "sec": "Recursive Descent",
    "q": "In Recursive Descent parsing, what does each non-terminal grammar rule map directly to in code?",
    "ans": "Dedicated function",
    "alt": [
      "A dedicated function in code"
    ]
  },
  {
    "sec": "Recursive Descent",
    "q": "Which helper operation inspects the current lookahead token without advancing the stream?",
    "ans": "peek()",
    "alt": [
      "peek"
    ]
  },
  {
    "sec": "Recursive Descent",
    "q": "Which helper operation asserts the expected token type and advances the stream?",
    "ans": "consume(type)",
    "alt": [
      "consume"
    ]
  },
  {
    "sec": "CST vs AST",
    "q": "What tree structure retains every single literal character from the input stream, including punctuation and parentheses?",
    "ans": "Concrete Syntax Tree",
    "alt": [
      "CST",
      "Parse Tree"
    ]
  },
  {
    "sec": "CST vs AST",
    "q": "What tree structure discards syntactic noise and retains purely essential operator-operand relationships?",
    "ans": "Abstract Syntax Tree",
    "alt": [
      "AST"
    ]
  },
  {
    "sec": "CST vs AST",
    "q": "What adjective describes the nature of an AST composed of different typed node objects?",
    "ans": "Heterogeneous tree",
    "alt": [
      "Heterogeneous"
    ]
  },
  {
    "sec": "AST Traversal",
    "q": "Which design pattern is commonly used to decouple analysis algorithms when traversing AST nodes?",
    "ans": "Visitor Pattern",
    "alt": [
      "The Visitor Pattern"
    ]
  },
  {
    "sec": "AST Traversal",
    "q": "What execution strategy recursively visits AST nodes to execute code live?",
    "ans": "Tree-Walk evaluation",
    "alt": [
      "Tree-walking",
      "Tree-Walk"
    ]
  },
  {
    "sec": "Code Generation",
    "q": "Name one low-level intermediate representation or target format emitted by compilers traversing an AST.",
    "ans": "WebAssembly",
    "alt": [
      "LLVM Intermediate Representation",
      "LLVM IR",
      "VM Bytecode"
    ]
  },
  {
    "sec": "Tooling",
    "q": "What interactive web tool mentioned in the lab unit allows visualizing live syntax trees online?",
    "ans": "AST Explorer",
    "alt": [
      "astexplorer.net"
    ]
  },
  {
    "sec": "Unit Lab",
    "q": "In the hands-on lab, what data interchange format is target output for the generated AST?",
    "ans": "JSON AST",
    "alt": [
      "JSON"
    ]
  },
  {
    "sec": "Front-End Compiler Architecture",
    "q": "What string literal input is given as the example source text in the compiler pipeline diagram?",
    "ans": "x = 10 + 2",
    "alt": [
      "\"x = 10 + 2\""
    ]
  },
  {
    "sec": "General Course Info",
    "q": "What course code and unit number is designated for this Lexing, Parsing, & ASTs topic?",
    "ans": "CSP 107 UNIT 2",
    "alt": [
      "CSP 107"
    ]
  },
  {
    "sec": "Lexical Analysis",
    "q": "What process binds identifiers and reserved keywords to symbol registers?",
    "ans": "Symbol Binding",
    "alt": []
  }
]
}